[package]
name = "scut-charge-monitor-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
ureq = { version = "3.1.4", features = ["cookies", "json"]}
base64 = "0.22"
serde = "1.0"
serde-envfile = "0.3.0"
serde_json = "1.0"
thiserror = "2.0"
log = "0.4.28"
fern = "0.7.1"
humantime = "2.3.0"
clap = { version = "4.5.51", features = ["derive"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

